# Generated by Django 5.1 on 2024-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('cstatus', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('found', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=200)),
            ],
        ),
    ]
